# Generated by Django 3.0.5 on 2023-04-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.IntegerField(help_text='Book unique id across the Library', primary_key=True, serialize=False)),
                ('book_number', models.PositiveIntegerField(help_text='Book number for books of the save kind', null=True)),
                ('Is_borrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
            ],
        ),
        migrations.CreateModel(
            name='issue_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('when_to_return', models.DateField(blank=True, help_text='Date the book is returned', null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
